// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3IBQ8u_rPgK-ycEKBjN8Q-rTtVCFEvWA',
    appId: '1:581450668907:web:5573d1763e0f8027500a2e',
    messagingSenderId: '581450668907',
    projectId: 'chatt-app-853a3',
    authDomain: 'chatt-app-853a3.firebaseapp.com',
    storageBucket: 'chatt-app-853a3.appspot.com',
    measurementId: 'G-DHWYZYTFLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIr--b_q4jTCUXIECETndBRtjp0wTeAuo',
    appId: '1:581450668907:android:e3c0f623ca154bed500a2e',
    messagingSenderId: '581450668907',
    projectId: 'chatt-app-853a3',
    storageBucket: 'chatt-app-853a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu27xuFJOEOOZl-VqeiSII35skzcC89Hk',
    appId: '1:581450668907:ios:946f9375318d7f61500a2e',
    messagingSenderId: '581450668907',
    projectId: 'chatt-app-853a3',
    storageBucket: 'chatt-app-853a3.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu27xuFJOEOOZl-VqeiSII35skzcC89Hk',
    appId: '1:581450668907:ios:946f9375318d7f61500a2e',
    messagingSenderId: '581450668907',
    projectId: 'chatt-app-853a3',
    storageBucket: 'chatt-app-853a3.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3IBQ8u_rPgK-ycEKBjN8Q-rTtVCFEvWA',
    appId: '1:581450668907:web:2476872c438d2bec500a2e',
    messagingSenderId: '581450668907',
    projectId: 'chatt-app-853a3',
    authDomain: 'chatt-app-853a3.firebaseapp.com',
    storageBucket: 'chatt-app-853a3.appspot.com',
    measurementId: 'G-QWS4RW3LL4',
  );
}
